name: pidetudeseo
favicon: null
layout_spectrum: 0.81842
typography_spectrum: 0.15022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed5e3'
    - '#b9b6b9'
    - '#e7827e'
    - '#7c797c'
    - '#454345'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
